// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_bYFCFIyub",
    "aws_user_pools_web_client_id": "6u09m071jtbkk6gqbknq4emcof",
    "aws_content_delivery_bucket": "sitecom4",
    "aws_content_delivery_bucket_region": "ap-southeast-1",
    "aws_content_delivery_url": "https://d2ssqqtacm1dln.cloudfront.net"
};


export default awsmobile;
